require 'ffi'
require 'ffi/opencl'

require 'heikou/core_ext/enumerable'
require 'heikou/buffer'
require 'heikou/cl'
require 'heikou/context'
require 'heikou/device'
require 'heikou/error'
require 'heikou/kernel'
require 'heikou/platform'
require 'heikou/program'
require 'heikou/queue'
require 'heikou/version'
