require 'ffi'
require 'ffi/opencl'

require 'opencl/cl'
require 'opencl/buffer'
require 'opencl/context'
require 'opencl/device'
require 'opencl/error'
require 'opencl/kernel'
require 'opencl/platform'
require 'opencl/program'
require 'opencl/queue'
require 'opencl/version'
